/*
 *  Define all Redux store action constants
 */

export const SET_USERS = 'SET_USERS';

export const REQUEST_CONTEXT_FETCHING = 'REQUEST_CONTEXT_FETCHING';
export const REQUEST_CONTEXT_FAILURE = 'REQUEST_CONTEXT_FAILURE';
export const REQUEST_CONTEXT_SUCCESS = 'REQUEST_CONTEXT_SUCCESS';
