export const SHOW_FACET_MENU = 'SHOW_FACET_MENU';
export const HIDE_FACET_MENU = 'HIDE_FACET_MENU';
export const SET_FACETS_EXPANDED = 'SET_FACETS_EXPANDED';
export const SET_FACETS_MORE_REVEALED = 'SET_FACETS_MORE_REVEALED';
export const TOGGLE_FACET_MENU = 'TOGGLE_FACET_MENU';

