
export const TOGGLE_LEFT_NAV_VISIBLE = 'TOGGLE_LEFT_NAV_VISIBLE';
export const TOGGLE_LEFT_NAV_EXPANDED = 'TOGGLE_LEFT_NAV_EXPANDED';
export const SHOW_TROWSER = 'SHOW_TROWSER';
export const HIDE_TROWSER = 'HIDE_TROWSER';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const SET_TOP_TITLE = 'SET_TOP_TITLE';
export const TOGGLE_APPS_LIST = 'TOGGLE_APPS_LIST';
export const SHOW_REPORTS = 'SHOW_REPORTS';
export const HIDE_REPORTS = 'HIDE_REPORTS';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SEARCH_FOR = 'SEARCH_FOR';
export const SEARCHING = 'SEARCH';
export const FILTER_REPORTS_BY_NAME = 'FILTER_REPORTS_BY_NAME';

export const SHOW_NEW_ITEMS = 'SHOW_NEW_ITEMS';
export const LOAD_APPS = 'LOAD_APPS';
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';
export const LOAD_APPS_FAILED = 'LOAD_APPS_FAILED';
export const SELECT_APP = 'SELECT_APP';
export const SELECT_TABLE = 'SELECT_TABLE';

export const LOAD_APP_USERS = 'LOAD_APP_USERS';
export const LOAD_APP_USERS_SUCCESS = 'LOAD_APP_USERS_SUCCESS';
export const LOAD_APP_USERS_FAILED = 'LOAD_APP_USERS_FAILED';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_REPORTS_FAILED = 'LOAD_REPORTS_FAILED';

export const LOAD_REPORT = 'LOAD_REPORT';
export const LOAD_REPORT_SUCCESS = 'LOAD_REPORT_SUCCESS';
export const LOAD_REPORT_FAILED = 'LOAD_REPORT_FAILED';

export const LOAD_REPORT_RECORDS_COUNT = 'LOAD_REPORT_RECORDS_COUNT';
export const LOAD_REPORT_RECORDS_COUNT_SUCCESS = 'LOAD_REPORT_RECORDS_COUNT_SUCCESS';
export const LOAD_REPORT_RECORDS_COUNT_FAILED = 'LOAD_REPORT_RECORDS_COUNT_FAILED';

export const LOAD_FIELDS = 'LOAD_FIELDS';
export const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';
export const LOAD_FIELDS_FAILED = 'LOAD_FIELDS_FAILED';

export const LOAD_RECORDS = 'LOAD_RECORDS';
export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS';
export const LOAD_RECORDS_FAILED = 'LOAD_RECORDS_FAILED';
export const LOAD_FILTERED_RECORDS_COUNT_SUCCESS = 'LOAD_FILTERED_RECORDS_COUNT_SUCCESS';
export const LOAD_FILTERED_RECORDS_COUNT_FAILED = 'LOAD_FILTERED_RECORDS_COUNT_FAILED';

export const SELECTED_ROWS = "SELECTED_ROWS";

export const NEW_BLANK_REPORT_RECORD = 'NEW_BLANK_REPORT_RECORD';
export const ADD_RECORD = 'ADD_RECORD';
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';
export const ADD_RECORD_FAILED  = 'ADD_RECORD_FAILED';
export const DELETE_RECORD = 'DELETE_RECORD';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_FAILED  = 'DELETE_RECORD_FAILED';
export const DELETE_RECORD_BULK = 'DELETE_RECORD_BULK';
export const DELETE_RECORD_BULK_SUCCESS = 'DELETE_RECORD_BULK_SUCCESS';
export const DELETE_RECORD_BULK_FAILED  = 'DELETE_RECORD_BULK_FAILED';
export const SAVE_REPORT_RECORD = 'SAVE_REPORT_RECORD';
export const SAVE_RECORD_SUCCESS = 'SAVE_RECORD_SUCCESS';
export const SAVE_RECORD_FAILED = 'SAVE_RECORD_FAILED';

export const SHOW_FACET_MENU = 'SHOW_FACET_MENU';
export const HIDE_FACET_MENU = 'HIDE_FACET_MENU';
export const SET_FACETS_EXPANDED = 'SET_FACETS_EXPANDED';
export const SET_FACETS_MORE_REVEALED = 'SET_FACETS_MORE_REVEALED';
export const FILTER_SELECTIONS_PENDING = 'FILTER_SELECTIONS_PENDING';
export const FILTER_SEARCH_PENDING = 'FILTER_SEARCH_PENDING';

export const HIDE_TOP_NAV = 'HIDE_TOP_NAV';
export const SHOW_TOP_NAV = 'SHOW_TOP_NAV';

export const SCROLLING_REPORT = 'SCROLLING_REPORT';

export const LOAD_FORM = 'LOAD_FORM';
export const LOAD_FORM_SUCCESS = 'LOAD_FORM_SUCCESS';
export const LOAD_FORM_FAILED = 'LOAD_FORM_FAILED';

export const LOAD_FORM_AND_RECORD = 'LOAD_FORM_AND_RECORD';
export const LOAD_FORM_AND_RECORD_SUCCESS = 'LOAD_FORM_AND_RECORD_SUCCESS';
export const LOAD_FORM_AND_RECORD_FAILED = 'LOAD_FORM_AND_RECORD_FAILED';

export const LOAD_EDIT_FORM = 'LOAD_EDIT_FORM';
export const LOAD_EDIT_FORM_SUCCESS = 'LOAD_EDIT_FORM_SUCCESS';
export const LOAD_EDIT_FORM_FAILED = 'LOAD_EDIT_FORM_FAILED';

export const LOAD_EDIT_FORM_AND_RECORD = 'LOAD_EDIT_FORM_AND_RECORD';
export const LOAD_EDIT_FORM_AND_RECORD_SUCCESS = 'LOAD_EDIT_FORM_AND_RECORD_SUCCESS';
export const LOAD_EDIT_FORM_AND_RECORD_FAILED = 'LOAD_EDIT_FORM_AND_RECORD_FAILED';

export const SAVE_FORM = 'SAVE_FORM';
export const SAVE_FORM_SUCCESS = 'SAVE_FORM_SUCCESS';
export const SAVE_FORM_FAILED = 'SAVE_FORM_FAILED';

export const MARK_PERF = 'MARK_PERF';
export const MEASURE_PERF = 'MEASURE_PERF';
export const NEW_ROUTE_PERF = 'NEW_ROUTE_PERF';
export const DONE_ROUTE_PERF = 'DONE_ROUTE_PERF';
export const LOG_MEASUREMENTS_PERF = 'LOG_MEASUREMENTS_PERF';

export const RECORD_EDIT_START = 'RECORD_EDIT_START';
export const RECORD_EDIT_CANCEL = 'RECORD_EDIT_CANCEL';
export const RECORD_EDIT_SAVE = 'RECORD_EDIT_SAVE';
export const RECORD_EDIT_CHANGE_FIELD = 'RECORD_EDIT_CHANGE_FIELD';
export const RECORD_EDIT_VALIDATE_FIELD = 'RECORD_EDIT_VALIDATE_FIELD';

export const OPEN_REPORT_RECORD = 'OPEN_REPORT_RECORD';
export const SHOW_PREVIOUS_RECORD = 'SHOW_PREVIOUS_RECORD';
export const SHOW_NEXT_RECORD = 'SHOW_NEXT_RECORD';

export const EDIT_REPORT_RECORD = 'EDIT_REPORT_RECORD';
export const EDIT_PREVIOUS_RECORD = 'EDIT_PREVIOUS_RECORD';
export const EDIT_NEXT_RECORD = 'EDIT_NEXT_RECORD';

export const SHOW_ERROR_MSG_DIALOG = 'SHOW_ERROR_MSG_DIALOG';
export const HIDE_ERROR_MSG_DIALOG = 'HIDE_ERROR_MSG_DIALOG';
