
export const TOGGLE_ROW_POP_UP_MENU = 'TOGGLE_ROW_POP_UP_MENU';
export const SEARCH_FOR = 'SEARCH_FOR';
export const FILTER_REPORTS_BY_NAME = 'FILTER_REPORTS_BY_NAME';

export const LOAD_APPS = 'LOAD_APPS';
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';
export const LOAD_APPS_FAILED = 'LOAD_APPS_FAILED';

export const SELECT_APP = 'SELECT_APP';
export const SELECT_APP_SUCCESS = 'SELECT_APP_SUCCESS';
export const SELECT_APP_FAILED = 'SELECT_APP_FAILED';

export const SELECT_TABLE = 'SELECT_TABLE';
export const UPDATED_TABLE_PROPS = 'UPDATED_TABLE_PROPS';

export const LOAD_APP_OWNER = 'LOAD_APP_OWNER';
export const LOAD_APP_OWNER_SUCCESS = 'LOAD_APP_OWNER_SUCCESS';
export const LOAD_APP_OWNER_FAILED = 'LOAD_APP_OWNER_FAILED';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_REPORTS_FAILED = 'LOAD_REPORTS_FAILED';

export const LOAD_REPORT = 'LOAD_REPORT';
export const LOAD_REPORT_SUCCESS = 'LOAD_REPORT_SUCCESS';
export const LOAD_REPORT_FAILED = 'LOAD_REPORT_FAILED';

export const LOAD_FIELDS = 'LOAD_FIELDS';
export const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';
export const LOAD_FIELDS_FAILED = 'LOAD_FIELDS_FAILED';

export const LOAD_RECORDS = 'LOAD_RECORDS';
export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS';
export const LOAD_RECORDS_FAILED = 'LOAD_RECORDS_FAILED';

export const SHOW_FACET_MENU = 'SHOW_FACET_MENU';
export const HIDE_FACET_MENU = 'HIDE_FACET_MENU';
export const SET_FACETS_EXPANDED = 'SET_FACETS_EXPANDED';
export const SET_FACETS_MORE_REVEALED = 'SET_FACETS_MORE_REVEALED';

export const HIDE_TOP_NAV = 'HIDE_TOP_NAV';
export const SHOW_TOP_NAV = 'SHOW_TOP_NAV';

export const SCROLLING_REPORT = 'SCROLLING_REPORT';

export const MARK_PERF = 'MARK_PERF';
export const MEASURE_PERF = 'MEASURE_PERF';
export const NEW_ROUTE_PERF = 'NEW_ROUTE_PERF';
export const DONE_ROUTE_PERF = 'DONE_ROUTE_PERF';
export const LOG_MEASUREMENTS_PERF = 'LOG_MEASUREMENTS_PERF';

export const SELECT_USERS_DETAILS = 'SELECT_USERS_DETAILS';
export const UNASSIGN_USERS = 'UNASSIGN_USERS';
export const UNASSIGN_USERS_SUCCESS = 'UNASSIGN_USERS_SUCCESS';
export const UNASSIGN_USERS_FAILED = 'UNASSIGN_USERS_FAILED';

export const LOAD_ALL_USERS = 'LOAD_ALL_USERS';
export const SEARCH_ALL_USERS_SUCCESS = 'SEARCH_ALL_USERS_SUCCESS';
export const SEARCH_ALL_USERS_FAILED = 'SEARCH_ALL_USERS_FAILED';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const SET_USER_ROLE_TO_ADD_TO_APP = 'SET_USER_ROLE_TO_ADD_TO_APP';

export const GET_APP_USERS_SUCCESS = 'GET_APP_USERS_SUCCESS';
export const GET_APP_USERS_FAILED = 'GET_APP_USERS_FAILED';
export const ASSIGN_USERS_TO_APP_SUCCESS = 'ASSIGN_USERS_TO_APP_SUCCESS';

export const TOGGLE_ADD_USER_TO_APP_DIALOG = 'TOGGLE_ADD_USER_TO_APP_DIALOG';
export const TOGGLE_ADD_TO_APP_SUCCESS_DIALOG = 'TOGGLE_ADD_TO_APP_SUCCESS_DIALOG';
