
export const TOGGLE_ROW_POP_UP_MENU = 'TOGGLE_ROW_POP_UP_MENU';
export const SET_TOP_TITLE = 'SET_TOP_TITLE';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const SEARCH_FOR = 'SEARCH_FOR';
export const SEARCHING = 'SEARCH';
export const FILTER_REPORTS_BY_NAME = 'FILTER_REPORTS_BY_NAME';

export const LOAD_APPS = 'LOAD_APPS';
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';
export const LOAD_APPS_FAILED = 'LOAD_APPS_FAILED';
export const SELECT_APP = 'SELECT_APP';
export const SELECT_TABLE = 'SELECT_TABLE';

export const LOAD_APP_USERS = 'LOAD_APP_USERS';
export const LOAD_APP_USERS_SUCCESS = 'LOAD_APP_USERS_SUCCESS';
export const LOAD_APP_USERS_FAILED = 'LOAD_APP_USERS_FAILED';

export const LOAD_APP_ROLES = 'LOAD_APP_ROLES';
export const LOAD_APP_ROLES_SUCCESS = 'LOAD_APP_ROLES_SUCCESS';
export const LOAD_APP_ROLES_FAILED = 'LOAD_APP_ROLES_FAILED';

export const LOAD_APP_OWNER = 'LOAD_APP_OWNER';
export const LOAD_APP_OWNER_SUCCESS = 'LOAD_APP_OWNER_SUCCESS';
export const LOAD_APP_OWNER_FAILED = 'LOAD_APP_OWNER_FAILED';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_REPORTS_FAILED = 'LOAD_REPORTS_FAILED';

export const LOAD_REPORT = 'LOAD_REPORT';
export const LOAD_REPORT_SUCCESS = 'LOAD_REPORT_SUCCESS';
export const LOAD_REPORT_FAILED = 'LOAD_REPORT_FAILED';

export const LOAD_FIELDS = 'LOAD_FIELDS';
export const LOAD_FIELDS_SUCCESS = 'LOAD_FIELDS_SUCCESS';
export const LOAD_FIELDS_FAILED = 'LOAD_FIELDS_FAILED';

export const LOAD_RECORDS = 'LOAD_RECORDS';
export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS';
export const LOAD_RECORDS_FAILED = 'LOAD_RECORDS_FAILED';

export const SELECTED_ROWS = "SELECTED_ROWS";

export const DTS_ERROR_MODAL = 'DTS_ERROR_MODAL';
export const DELETE_RECORD = 'DELETE_RECORD';
export const DELETE_RECORD_BULK = 'DELETE_RECORD_BULK';

export const SHOW_FACET_MENU = 'SHOW_FACET_MENU';
export const HIDE_FACET_MENU = 'HIDE_FACET_MENU';
export const SET_FACETS_EXPANDED = 'SET_FACETS_EXPANDED';
export const SET_FACETS_MORE_REVEALED = 'SET_FACETS_MORE_REVEALED';

export const HIDE_TOP_NAV = 'HIDE_TOP_NAV';
export const SHOW_TOP_NAV = 'SHOW_TOP_NAV';

export const SCROLLING_REPORT = 'SCROLLING_REPORT';

export const MARK_PERF = 'MARK_PERF';
export const MEASURE_PERF = 'MEASURE_PERF';
export const NEW_ROUTE_PERF = 'NEW_ROUTE_PERF';
export const DONE_ROUTE_PERF = 'DONE_ROUTE_PERF';
export const LOG_MEASUREMENTS_PERF = 'LOG_MEASUREMENTS_PERF';
