export const MULTICHOICE_RADIOGROUP = {
    NONE_OPTION_VALUE: ''
};
export const ERROR_TIP_TIMEOUT = 2000;

export const NOTIFICATION_MESSAGE_DISMISS_TIME = 2000;
export const NOTIFICATION_MESSAGE_FAIL_DISMISS_TIME = 2500;
