source 'https://supermarket.chef.io'

group :external do
  cookbook 'datadog'
end

group :internal do
  cookbook 'nodejs', git: 'git@github.com:QuickBase/cookbook-nodejs.git', branch: 'coreui-deployment'
  cookbook 'splunkclouduf', git: 'git@github.com:QuickBase/cookbook-splunkclouduf.git', branch: 'master'
end
